name: decision
description: Decision sdk for TIKI
version: 0.0.4
homepage: https://github.com/tiki/decision
repository: https://github.com/tiki/decision

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  logging: ^1.0.2
  url_launcher: ^6.0.20
  tiki_kv:
    git:
      url: https://github.com/tiki/tiki_kv
      ref: 0.0.2
  tiki_style: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0